- name: retrive secrets
  hosts: localhost
  tasks:
    - debug:
        msg: "{{ lookup('hashi_vault', 'secret=kv/data/Test-secret:MYPASS token={{vault_token}} url=https://vault.sy80devops.online:8200 validate_certs=false')}}"